APPDESCRIP-28: update erm-usage/files interface id to be valid for Eureka platform
folio-org/ui-erm-usage pull request #476
Opened 2024-07-29 10:06 UTC by yaroslav-kiriak

[APPDESCRIP-28](https://folio-org.atlassian.net/browse/APPDESCRIP-28)

Related PR: https://github.com/folio-org/app-erm-usage/pull/1

Purpose: update erm-usage/files interface id to be valid for Eureka platform

2024-07-29 10:13 UTC, pfilippov-epam approved these changes

2024-07-29 10:20 UTC, mykolam-epm approved these changes

2024-08-01 11:25 UTC, alb3rtino requested changes
Same as https://github.com/folio-org/mod-erm-usage/pull/179#pullrequestreview-2212459727

Please increase app major version and merge together with related PRs.

Also please update `CHANGELOG.md`.

2024-08-02 12:40 UTC, alb3rtino requested changes

2024-08-02 12:40 UTC, alb3rtino commented on CHANGELOG.md
>  ## 9.1.0 (IN PROGRESS)
`## 10.0.0 (IN PROGRESS)`

2024-08-02 13:40 UTC, alb3rtino approved these changes

2024-08-08 21:05 UTC, closed without merging

2024-08-08 21:16 UTC, MikeTaylor commented
Why did you close this instead of merging it? It seems to be necessary, now the other changes have been made.

2024-08-08 21:24 UTC, alb3rtino commented
Please see here https://github.com/folio-org/ui-erm-usage/pull/477

2024-08-08 21:37 UTC, MikeTaylor commented
OK, thanks.